### PR TITLE
Support Non-English names | Optimize loop

### LINKED ISSUE #102: Feature Reuest - Allow multiple deadnames and prefferd names.
Some names are written differently in different languages (for example, the name Mikayla in Hebrew is written like this: מיכאלה)
So adding an option for bilinguals to add multiple versions for their names would be great.

### LINKED ISSUE #106: The extension doesn't work with russian, arabic languages (and many others, I think)
I can type my deadname and dead last name in text boxes in russian (or arabic) and type my new name and new last name in text boxes in russian (or arabic) too. But extension doesn't see my deadname on websites at all and doesn't replace it with my new name. I've checked different websites. However, when I am trying to change english variant of my deadname with my new russian name, it works perfectly. I think that this extension only works with the english language.

### LINKED ISSUE #124: Non-alphanumeric characters
I wanted to put an asterix after my name or to put my name in brackets, to be able to tell when someone is deadnaming me or to be sure to know if it changes the name of other people who share my deadname, but when adding non-alphanumerical characters, the extension only works while loading. When a page is loaded, it goes back to my deadname.

### LINKED ISSUE #154: Non-English Names
Kinda a suggestion I guess? Since my deadname doesn't use a languege that comes from latin heritage, It doesn't work. Maybe add languege detection (I think it needs that? Not sure, sorry) over time?

### LINKED ISSUE #166: Cyrillic Support/Non-english names
I don't really mind it but I think adding support for Cyrillic alphabets and names from eastern european languages would be really cool

### LINKED ISSUE #168: Deadname-Remover doesn't change my last name
Hello,
I have an issue with Deadname-Remover. It changes my first name just fine and it's helped a lot, but it doesn't do the same for my last name. I don't know if this is because it doesn't actually change last names at all or because I did something wrong. I understand that since most of the people who use this have the same last name in their old and preferred name, you wouldn't need to change it, but I live in a country where there are feminine and masculine versions of last names, and seeing my old last name makes me really dysphoric. Maybe it's an issue on my side but I don't know what I might've done wrong.

### PR DESCRIPTION
**Pull request by Gusted**
- The word boundary assertation has just support for [WordCharacters](https://tc39.es/ecma262/#sec-notation) in the [specifications of \b assertation](https://tc39.es/ecma262/#sec-assertion) causing it to not handle non-WordCharacters well.
- Using a custom check and not using native regex can bypass this weird behavior.
- Fixes a issue with popup.ts whereby the onOff switch won't register it's event.
- Optimize the loop to just loop the function that actually needs to be looped.
- Resolves #154
- Resolves #166
- Resolves #168
- Resolves #124
- Resolves #106
- Resolves #102

### CODE REVIEW

**Comment by Gusted** [comment]
TODO: Needs more testing.

**Comment by Gusted** [comment]
LGTM and passes a quick test without any issues.

**Comment by WillHayCode** [comment]
You are a legend, @Gusted . I'll do some tests and put up a new version in the next few days.

**Comment by Gusted** [comment]
> 
> 
> You are a legend, @Gusted . I'll do some tests and put up a new version in the next few days.

No problems, just trying to expand my Javascript knowledge.

**Pull request merged**
