### PR TITLE
More inprovements

### LINKED ISSUE #76: MutationObserver doesn't consistently fire on Facebook
For some reason, when I visit a page on Facebook the replacement rarely works since merging #72 

If I load the extension with the page already opens it does a partial replacement (first names only), and if a Facebook page is opened while the extension is already loaded it won't work at all.

### PR DESCRIPTION
**Pull request by Gusted**
- Make sure to have a existing Node that have a parentElement, otherwise it's already been removed and no insertBefore is needed.
- Fix CheckForNode logic by recursive checking ChildrenNodes(That can contain text nodes as well).
- Add a check to not do anything DOM related before the DOM is actually loaded and interactive.
- Add checkElementForTextNodes to do the TextNode finding on inital DOM Loading.
- Add lib as CompilerOption to make sure compatible ES6 functions.
- Fixed some tab/spaces formatting.
- Resolves #76

### CODE REVIEW

**Comment by Gusted** [comment]
duckduckgo.com and facebook.com is working now 🎉. Now hoping not other sites will get broken.

**Comment by WillHayCode** [comment]
For some reason this version and all previously functional versions aren't working on my computer - once I've fixed that issue with my computer, I'll test this and hopefully merge it in the next day or two. Thank you again for all your hard work.

**Comment by Gusted** [comment]
> For some reason this version and all previously functional versions aren't working on my computer

Could you explain a bit more? IDE Issues? Browser issues?

> Thank you again for all your hard work.

No problems, planned on using this as well when this PR is merged and published :)

**Comment by WillHayCode** [comment]
After 20 minutes of debugging, I have uncovered the issue: I was accidentally on the wrong branch 😅

This seems to work perfectly! I'm gonna merge and then run some more tests before submitting to the various extension stores

**Comment by Gusted** [comment]
> I was accidentally on the wrong branch 😅

Lmao that's unfortunate.

> This seems to work perfectly!

Yay

**Pull request merged**
