### PR TITLE
Improvements :tada:

### LINKED ISSUE #7: [Bug?] Extension maxes out CPU thread when enabled (Firefox 75, Ubuntu 20.04)
basically what it says on the tin: whenever the extension is enabled, one of my cpu cores is constantly maxed out. [evidence](https://i.imgur.com/mwN0U9h.mp4)

### LINKED ISSUE #17: Gmail
hey! just wanted to let you know that in (at least my) Gmail, there's a pull-down tab on the right which doesn't display my name correctly. (Image attached) this might be an issue on other sites too. Thanks!
image

### LINKED ISSUE #30: Treewalker
You might consider using a treewalker for your replaceName() function in inject.ts. The treewalker does all of the iteration through nodes and children that you're doing with the for loop, but all in four lines and without any messy nesting for loops. I've attached some example code in plain js. [dbg2.txt](https://github.com/WillHayCode/Deadname-Remover/files/4761965/dbg2.txt)

Full disclosure, I have had some issues with treewalkers not finding text nodes in the past. However, these were browser/webpage issues, not problems with the code itself, and have since been fixed.

I love the extension, and I'm happy to see someone finally putting in the effort to put this together. Keep up the good work!

### LINKED ISSUE #33: Location Feature?
Hi! I think a great feature for this program would be activating or deactivating depending on what wifi network/ip address/location you're at. Because I use the same computer at work and at home, and since I'm not out to my coworkers yet, I need to go into the plugin and change the name back to my deadname whenever I'm at work. Then when I get home, I need to change it back to my actual name so my dysphoria doesn't kill me when I'm at home. Honestly, a simple, quick pop-up on/off switch from the plugins bar in chrome would work just as well. Sorry for the bother, but I think that would be cool!!!

### LINKED ISSUE #45: Very Slow
While it works fine overall, my main issue is that this extension alone slows down my entire computer so much while I have firefox open, is there any optimizations that can be done? or at least make an option to only scan the website while it is first being loaded

### LINKED ISSUE #64: Maybe have an option to toggle?
I'm trying to do my school work in Google Drive, and the extension keeps editing over my deadname. It makes using Drive difficult, and I don't want to manually add sites it's allowed to use, so maybe add an option to toggle the extension, kind of like AdBlock.

### PR DESCRIPTION
**Pull request by Gusted**
- Code Clean up trough types(DEFAULT_SETTINGS for example)
- Some updated CSS for the options and using external `.css`
- Updated manifest.json to inject the script into all iframes as well to resolve #17 
- Using Mutation Observer's that are lightweight for CPU to resolve #7 and as it's a native API by the browser you shouldn't notice the dead name flash :D and resolve #45 and resolve #30
- Added build script in package.json to get integrated with VSCode 
- Moved the check of nodes and replacing it into it's own function as it has now multiple references.
- Added a Enable/Disable button, Resolves #33 (asked for this, as with current API's that kind of automation isn't possible). Resolves #64 It would be great to have a SiteList system, but that requires some more UI and UX Design.

Welp It's 1 messy code also about the flash. 
[aaa.zip](https://github.com/WillHayCode/Deadname-Remover/files/5113369/aaa.zip) A example page where you can follow how the MutationObserver and Listener do their job.

Regards,
Gusted

### CODE REVIEW

**Comment by Gusted** [comment]
Hi @WillHayCode!

Mind to review this PR? Or any update on it 👀 

Regards,
Gusted

**Comment by WillHayCode** [comment]
Hi Gusted! I've only just noticed this - I'll check this out now and (assuming there's no issues) merge it! Thank you for taking the time to make these additions, they've been on my "todo" list for far too long.

**Comment by WillHayCode** [comment]
This is absolutely an improvement, but for some reason it's working somewhat inconsistently. For example, John Smith -> Mary Sue I'm ending up with a lot of "Mary Smith's". I'm looking into the situations in which they occur, but once that's resolved I'm going to merge this and update the Chrome and Firefox plugins ASAP.

**Comment by WillHayCode** [comment]
Is there a particular reason for the shouldListen parameter on replaceName? Currently it's always set to true

**Comment by WillHayCode** [comment]
I found a bit of a refactor to fix that, I'll be uploading that soon.

**Comment by Gusted** [comment]
> Is there a particular reason for the shouldListen parameter on replaceName? Currently it's always set to true

Woops, I actually wanted to make when the extension got disabled it reverts all cases of the new name back to the dead name so it won't leave any changes behind. But I completely forgot to add that implementation.

I will also have a look on Facebook why it's not working as it shouldn't override any native API code.


> John Smith -> Mary Sue I'm ending up with a lot of "Mary Smith's".  

Hmm weird, it didn't really changed anything to the logic of creating regex that should leave out the last name. But it seems you found a refractor to fix that so I had indeed some bad code 😅. 🎉

**Pull request merged**
