### PR TITLE
Created more accessible markup with new styling

### PR DESCRIPTION
**Pull request by arimgibson**
Was feeling like the previous design was a little bit bland compared to what it could be, decided to spice it up a little bit. By changing the page markup, the extension is also more accessible for those who rely on screen readers.

I had trouble hooking it up to the `option.ts` file as the code in there got confusing and seemed unnecessarily complicated, but I figured I'd submit these changes and get some help with the TS. I started working on some edits to the TS but this is the first Chrome extension I've worked on, not quite sure how the storage there works.

Thanks for this extension! I don't use personally but wanted to contribute after a friend shared in a LGBTQ+ group chat.

### CODE REVIEW

**Comment by AriGibson** [comment]
Forgot to mention this PR ruins the popup styling, will commit those changes when I have though

**Comment by AriGibson** [comment]
Design can be viewed on the development site I was using: [deadname-remover-redesign.web.app](https://deadname-remover-redesign.web.app)

**Comment by Gusted** [comment]
Hi @AriGibson!

I've seen the high-contrast implementation, but I'm unsure if this is good to implement as it's uses some obsolete features like the dataSet property and AFAIK screen readers should be able to understand the text. Also as for the current DeadName implementation it's been a box that has unlimited options to add forms of deadnames and with this new UI it's been limited to 5 which is a limitation I rather don't have.

I will port the current javascript code to TS.

Regards,
Gusted

**Comment by AriGibson** [comment]
Hiya @Gusted !

Responding to some of your points...:
- What would you replace `data-*` attributes with? What would you say makes them obselete? I would argue they're the best, most correct way to group elements. They're supported by [essentially every browser](https://caniuse.com/dataset) ([MDN])(https://developer.mozilla.org/en-US/docs/Web/API/HTMLOrForeignElement/dataset) and allow the code to loop through `document.querySelectorAll` instead of a `for i` loop choosing elements by ID
- I've spent a good amount of time on NVDA testing accessibility. The old design, by not using landmarks or semantic HTML, doesn't pass some of the most basic accessibility concepts imo. By using `aria-*` attributes in my design, I feel like it's significantly easier to use with a screen reader. I'd encourage you to give it a try as well if you haven't accessibility tested with a screen reader before, changed the way I think about the web 😝
- I definitely see what you're saying about the multiple deadname implementation. I ran the design by some friends who preferred being able to see them all at once, although I'm sure there's a good UX-friendly solution. I'm happy to work on that, just stuck trying to figure out the best solution.

Regarding the JS code, I was more referencing the code in the current `options.ts` file, which my markup changes don't work with. I have very limited TS experience, but some of the code in there seemed unnecessary to me. I'd have to give it some more looking and testing with what I would have done to see if I'm just crazy, figured I wouldn't worry about that part right now.

Thanks!
Ari

**Comment by Gusted** [comment]
> What would you replace `data-*` attributes with?

With a simple unique attribute or class.

> What would you say makes them obsolete?

It's was used back in the day, however most if not all has been replaced with alternatives which makes more sense.


> I would argue they're the best, most correct way to group elements.

If it's used for just grouping elements a simple `<div>` should do this with something like `class="group-options"`.

>  allow the code to loop through `document.querySelectorAll` instead of a `for i` loop choosing elements by ID

Why you want to have all elements?

>  By using `aria-*` attributes in my design, I feel like it's significantly easier to use with a screen reader. I'd encourage you to give it a try as well if you haven't accessibility tested with a screen reader before, changed the way I think about the web

Uhm, same reason with `data-` it's obsolete and replaced with better alternatives. MDN even warns about using this https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA.



>     * I definitely see what you're saying about the multiple deadname implementation. I ran the design by some friends who preferred being able to see them all at once, although I'm sure there's a good UX-friendly solution. I'm happy to work on that, just stuck trying to figure out the best solution.

It's hard to sense back, because their has been now an unlimited options and people might have now used more than 5 deadnames. E.g. an `list` with some `textarea` element could fix the unlimited options and seeing all names.

> but some of the code in there seemed unnecessary to me.

It's indeed a mess.

**Comment by AriGibson** [comment]
> What would you replace data-* attributes with?
With a simple unique attribute or class.

By using a `data-*` attribute, it removes the confusion that these attributes are standard HTML. `data-*` is used specifically and exclusively to store data in an element, whereas classes have a variety of uses. Considering I'm not styling these elements based on the data attributes, I believe that would be an inappropriate use of classes.

[Why `data-*` opposed to standard attribute](https://stackoverflow.com/questions/33151713/html-data-attribute-vs-simple-custom-attribute) and [why `data-*` opposed to classes](https://stackoverflow.com/questions/17184918/best-practice-class-or-data-attribute-as-identifier)

> What would you say makes them obsolete?
It's was used back in the day, however most if not all has been replaced with alternatives which makes more sense.

Even if they've been around for a while doesn't make them obsolete. Their still common practice and are recommended by MDN. I strongly believe their purpose is still clear and relevant.

> I would argue they're the best, most correct way to group elements.
If it's used for just grouping elements a simple <div> should do this with something like class="group-options".

`div`s aren't accessible though, which is the main redesign I thought this extension could use a redesign with semantic HTML that follows web accessibility standards.

> allow the code to loop through document.querySelectorAll instead of a for i loop choosing elements by ID
Why you want to have all elements?

To easily pull values from the deadname fields. I admit this might be something that could be considered a flaw in my design. I see what you're saying by having a `textarea` and asking users to add a comma-delimited list, although I feel like that's not as straightforward to the user. I feel like it's important to make things as simple as possible, but I'll definitely think about changing that and might try some other versions of my design.

> By using aria-* attributes in my design, I feel like it's significantly easier to use with a screen reader. I'd encourage you to give it a try as well if you haven't accessibility tested with a screen reader before, changed the way I think about the web
Uhm, same reason with data- it's obsolete and replaced with better alternatives. MDN even warns about using this https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA.

To be clear, MDN argues that semantic HTML should be used over ARIA _where semantic HTML exists_. My code follows those standards, `aria-*` attributes are completely different and essential to proper web accessibility. I've done lots of testing with NVDA; `aria-*` labels specifically are crucial to helping a user tell the purpose of each field without sight.

I appreciate the discussion and will definitely take some of what you said into consideration while I finish prepping this PR. I also think there are some things that I fully stand behind as being best practice. I'm really curious on your thoughts though, as I believe what I've mention is considered best practice by the majority of the web dev community. Cheers!

**Comment by Gusted** [comment]
>  I also think there are some things that I fully stand behind as being best practice.

I can live with those standards I think... even it's a bit whacky for code purposes and tricky.

The multiple names implementation should have the old behaviour of having a good *unlimited* usage. A simple design should do it I will work it out in the code to have it functioning.

Let me know when the Design is ready and I will have some code porting and cleaning to `options.ts`.

Regards,
Gusted

**Comment by Gusted** [comment]
@AriGibson I saw you added a option for `highlighting` I've pushed this feature to the master branch #198

**Comment by AriGibson** [comment]
Looks great! Thanks for taking care of that, I hadn't gotten around to adding the actual feature in. I'll add a spot to set hex color as well, am happy to make that change in the code too unless you want to

**Comment by Gusted** [comment]
> I'll add a spot to set hex color as well, am happy to make that change in the code too unless you want to

Thats fine, some customization is great.

As their is a highly requested feature for a site list. What are the UI recommendations for that? I've tried several implementations myself but gave up after each time.

**Comment by AriGibson** [comment]
I'll see what I can come up with... I like the idea of having unlimited names though. Will go back to my non-dev friends for some ideas haha, want to see if they have any good clue on how to use like a comma-delimited list without much instruction

**Comment by AriGibson** [comment]
My current timeline for finishing up this PR is looking like Sunday, feeling stuck trying to figure out what does and doesn't make sense to change.

I'd like to send over some revisions to the TS code as well, although I'm a tad bit scared to touch it. A lot of it seems unnecessary to me, but I'm sure it's there for a good reason haha. I might also just be naive; I guess we'll see if I dive in a bit deeper.

I'm sort of seeing two solutions here:
1. Spent a good chunk of time tweaking the TS to work with my new markup.
2. Roll back some of my markup changes so it's easier to integrate with current TS and have something merge-ready faster.

**Comment by Gusted** [comment]
> I'd like to send over some revisions to the TS code as well, although I'm a tad bit scared to touch it. A lot of it seems unnecessary to me, but I'm sure it's there for a good reason haha. I might also just be naive; I guess we'll see if I dive in a bit deeper.

A lot of the codebase has been whacky and not probably most of it unnecessary(Just the UI side options.ts/popup.ts) as UI isn't my best side. You can make the changes in JS if you like to and I will port it without any problems to TS with the correct code e.g. the storage handling as that's currently done with `const port = chrome.runtime.connect({name: 'popup'});` and some complicated sendRequest function, as it lacks certain functionally that context. 

I think the first solution is the best one as the codebase definitely need a rewrite, however just tweak it so far you can. I can do the rest if you like to.

For now I will resolve the conflicts in this PR.

Regards,
Gusted

**Comment by AriGibson** [comment]
Perfect, let's do that. I'll write up a bunch of JS and let u port to TS, if you think it's even worth having in TS. I'm a big JS nerd though and have never been fully onboard with the benefits of TS lol

If possible, I'd prefer to just have until the weekend before you take a look. I'll have something good ready for and am sure I can get through some of the issues myself ☺️

**Comment by Gusted** [comment]
> Perfect, let's do that. I'll write up a bunch of JS and let u port to TS,

Sure thing, make sure to add some comments if the code `looks confusing` =).

> if you think it's even worth having in TS. I'm a big JS nerd though and have never been fully onboard with the benefits of TS lol

Type checking etc and having other functionally like ESLint works better. and for IDE's like vscode the Intelsense works better, because it can be `checked`. It's more for the development process then the actually end-result. 

> If possible, I'd prefer to just have until the weekend before you take a look. I'll have something good ready for and am sure I can get through some of the issues myself :relaxed:

Sure things! Don't be afraid to ask.

**Comment by Gusted** [comment]
Hi @AriGibson!

It's by now Sunday evening for me, should I have another look next week on this PR?

Regards,
Gusted

**Comment by AriGibson** [comment]
Woops @Gusted meant to text a bit earlier... didn't realize the time difference haha.

I've made some good progress but haven't pushed yet as I don't want to mess up the current file structure. I've just been design in a different folder; the changes still need to be merged into this repo. I'll definitely touch base in a little bit when I have some substantial updates pushed.

**Comment by Gusted** [comment]
👌🏽

**Comment by AriGibson** [comment]
@Gusted I would appreciate some feedback on the popup form though 😊
https://deadname-remover-redesign.web.app/popup.html

Merged those changes here as well but they don't have the scripts for theme changing yet

**Comment by Gusted** [comment]
> @Gusted I would appreciate some feedback on the popup form though blush
> https://deadname-remover-redesign.web.app/popup.html
> 
> Merged those changes here as well but they don't have the scripts for theme changing yet

LGTM the design.

So the speed of the `slider` seems personally a bit slow due to the `ease-in-out` animation, that haves a lower speed on the start and end, I think it can be reduced to `0.6s` to encounter this while having the same effect.

I think an extra `theme` can be added called HighContrastInverse, that is the same of HighContrast but a dark-theme of it so users don't need to blind their eyes.

e.g. how `Pop!_OS` *Linux Distro* has this option.
HighContrast:
image
HighContrastInverse:
image

**Comment by AriGibson** [comment]
@Gusted meant to check in a few days ago, crazy week.

I have a bunch done but wanted to take a look at the extension "backend" to make sure my changes don't make y'all completely rework how the extension works. I think I did a good job, but I don't want to make your life impossible.

Will make my final changes and push them tomorrow

**Comment by Gusted** [comment]
> I have a bunch done but wanted to take a look at the extension "backend" to make sure my changes don't make y'all completely rework how the extension works. I think I did a good job, but I don't want to make your life impossible.

It's fine. The current background.ts is modular and should only need a few changes from the current UI that is published at [the site](https://deadname-remover-redesign.web.app/popup.html).

**Comment by AriGibson** [comment]
Perfect. I keep finding more things to change, so I'm going to stop setting timelines...

**Comment by AriGibson** [comment]
@Gusted Alright, it's all ready if you want to put it to TS. The JS is pretty clean so I'd almost prefer if it wasn't put back into TS, but that's up to you. Let me know if you get stuck anywhere, but hopefully it's pretty straightforward.

All the settings change the Chrome local storage directly, so hopefully that makes it easy to integrate with everything else. 😊

**Comment by Gusted** [comment]
> @Gusted Alright, it's all ready if you want to put it to TS. The JS is pretty clean so I'd almost prefer if it wasn't put back into TS, but that's up to you. Let me know if you get stuck anywhere, but hopefully it's pretty straightforward.

Ill it will be ported as cleanly with just some adjustments probably to have `type checking` in place and make sure it won't break in further adjustments.



> All the settings change the Chrome local storage directly, so hopefully that makes it easy to integrate with everything else. blush

👌🏽

**Comment by Gusted** [comment]
As it seems like their are some issues with pushing commits to an PR
Please use this two Patch( in the exact order)
`git apply [the long generated string].patch`
and then push it.

[weow.zip](https://github.com/WillHayCode/Deadname-Remover/files/5596718/weow.zip)

**Comment by AriGibson** [comment]
@Gusted strange... all good now? Besides the one conflict

**Comment by Gusted** [comment]
> @Gusted strange... all good now? Besides the one conflict

LGTM to me, If you have a look as well and see if everything works as you intended then I can merge this PR.

**Comment by AriGibson** [comment]
God I'm so sorry @Gusted ... I've been swamped! I'm taking a look now and will get back to you within a few hours 💕

**Comment by AriGibson** [comment]
I've found a couple bugs and a couple things I neglected to add, looping you in but will give it by best first. WIll edit this comment as I go through these tasks.

1. The theme doesn't save in either the main options panel or the popup; it gets reset back to "transgender" each time.
2. The extension's first load includes ", " in front of each of the deadname boxes, probably something to do with the `join()`
3. Add a bit more padding to the bottom of the "View All Options" box on the bottom of the popup
4. Add color background to replaced names depending on theme, currently is only set to the yellow highlight

**Comment by Gusted** [comment]
> * The theme doesn't save in either the main options panel or the popup; it gets reset back to "transgender" each time.
> 
> * The extension's first load includes ", " in front of each of the deadname boxes, probably something to do with the `join()`

Oops, I pushed some changes to `WillHayCode/Deadname-Remover:Arigibson/master` instead of `Arigibson/Deadname-Remover:master`. This should be fixed now. 

I assume the third one is CSS.
The 4th hmmm, I don't know it if making it to the `theme` is a good idea it can decrease contrast. It's currently using `mark` element to let the browser handle the contrast.

**Comment by Gusted** [comment]
> The 4th hmmm, I don't know it if making it to the `theme` is a good idea it can decrease contrast. It's currently using `mark` element to let the browser handle the contrast.

Alternative can be discussed on a new issue as it doesn't make to seem much sense for a UI PR to change this.

**Comment by AriGibson** [comment]
Omg, you're magic! I'll go do some more testing and follow up in a few minutes. I was literally just waiting for my computer to boot to make those fixes when I got the email that you pushed some stuff 😅

Re: the fourth one, that's in relation to #199. I see what you're saying for sure though; let's continue that convo there.

**Comment by AriGibson** [comment]
Still having trouble, will take a look myself and let you know

**Comment by AriGibson** [comment]
@Gusted alright, it seems like all the issues I spotted were from the porting process, as I gave another check with my original JS code, and none of those errors are present. I'm happy to try and port my code to TS, unless you want to try again. Don't wanna offload too much of my junk onto you haha

**Comment by Gusted** [comment]
> I'm happy to try and port my code to TS, unless you want to try again. Don't wanna offload too much of my junk onto you haha

I can port it, I have time enough now school has vacation :)

**Pull request merged**
