### PR TITLE
Auto-update tabs & Nickname Support & New building Process

### LINKED ISSUE #1: Feature Suggestion
Hi! I love your program, it's extremely helpful (especially for email). I was wondering if there was any way to have the program check if the last name matches the user's last name before replacing the deadname? As it is right now, every instance of my deadname gets replaced with my name, not just the ones referring to me. Would love to see a feature preventing this, as I have a massively popular deadname.

### LINKED ISSUE #6: [Suggestion] Additional Names
This extension has been amazing for me but I see both my full name and a shortened version pretty often. I've tried messing with it a bit but can't seem to get it to change both. An option to filter additional names would be great.

### LINKED ISSUE #10: Nicknames feature suggestion
I would love to see a feature that allows me to replace dead nicknames as well. I had a long and short form of my old name, and want to replace those with the long and short form of my new name. Love the plug in!

### LINKED ISSUE #11: Nicknames
My deadname had nicknames that I also want to be able to get rid of so a way to enter in multiple nicknames would be great. love the extension, thanks!

### LINKED ISSUE #12: dead-nickname remover
maybe add fields for any nicknames one used to go by and may want removed, and what they want to see instead? for example, say someone's deadname is Elizabeth, and the extension removes that, but someone could still call them Liz and the program, in its current form, wouldn't change it.

### LINKED ISSUE #13: Suggestion: Multiple/short-long name support
Example: if my deadname was "Benjamin" commonly shortened to "ben" this would only work for one of the two, with "ben" being corrected, "Benjamin" would become "<newname>jamin"

### LINKED ISSUE #18: Name issues
So my full deadname is Alexander but I frequently went as Alex and I find it just as much a vexation on my existence as my full deadname. Can I get the option to filter alternate versions of my deadname that I used to go by. Also add an alternative name that I also go by as well

### LINKED ISSUE #25: Multiple options for deadname
I have a couple nicknames/variations of my name that are used.
is there any way to add more deadname options?
thanks.

### LINKED ISSUE #26: Suggestion for Email/Social Services
Hi, I love the app, but I'm one of those people who's deadname has a common nickname, and as a result, the app doesn't always catch the words people use. Is there a way you can insert a way for someone to insert, say, a dead nick-name as well?

For reference: It'll correctly replace Gabriel, but will not replace Gabe. Other examples I can think of are Marcus and Mark, Jacob and Jake, etc.

Thank you for your time!

### LINKED ISSUE #27: Problems with accent marked letters
Hello, i'm writing you about an oversight regarding letters with accent marks (á,é,í,ó,ú)

If the extension has a name registered as deadname with one of those letters (for example, "Adrián"), it doesn't change it when the mark is absent ("Adrian")

Is there a way to solve this error?

### LINKED ISSUE #32: Shortened Name Remover feature
Just added the extension and noticed a minor thing. Since my deadname can be shortened, and often is in places, the extension only works on either the full version or the shortened version of the name (depending on which one i put in it). So i think an option for removing short versions of names as well would be nice. Otherwise it seems really cool

### LINKED ISSUE #38: Multiple deadnames
Hello! First of all, I want to say that I love your extension, and thank you so much for making it! One suggestion I have is to allow the user to enter multiple deadnames. This could be useful if the user has a nickname based on their deadname or has changed their name multiple times (like me). Thank you!

### LINKED ISSUE #39: Cases where first name and middle name are in the same field don't work
I was trying out the addon (in Firefox) and visited my university's Blackboard instance, where the addon correctly changes my first and last names, but leaves my middle name untouched.

image

It seems to me that this is because Blackboard treats any first and middle names as one first name field, and the addon doesn't check for multiple words in the first name field.

image

### LINKED ISSUE #42: Deadname Variations
Hey so I'm a trans girl, and first off, thanks for making this extension, it means a lot and it's very helpful. But I do have 1 issue with it. I have a deadname that is frequently shortened. Due to this, it is inconsistent as to which version is listed. If the extension could be altered to allow multiple deadnames that get replaced, that would be nice. I'm unsure how difficult that would be, but I hope it's feasible. 

Sincerely,
Mia

### LINKED ISSUE #43: Deadname Nicknames
Idea:

Add support for multiple deadnames in case they use a nickname or shortened name

### LINKED ISSUE #48: Flipped names
HI, i am writing this because i think a necessary feature is having an option where you can input your name/deadname for when your name is flipped on sites. for example, someones deadname was alex hampton, new name was alexis hampton. on a site it said HAMPTON Alex, instead of HAMPTON Alexis, that would be quite triggering for them. maybe either add a feature to ensure that doesnt happen, or make the code a tad better. 
thanks for reading.

### LINKED ISSUE #50: Suggestion
Hi I had a suggestion that maybe you could make it o that multiple names can be changed or hidden.

### LINKED ISSUE #53: suggestion
perhaps instead of only one deadname being blocked, would there be a way to make it possible to have multiple blocked and changed?

### LINKED ISSUE #58: Multiple Deadname Suggestion
As somebody who has spent a lot of time trying to come up with names, i've gone through several. the ones that i had and ditched still have the same impact on me that my birthname does. i think it'd be beneficial to be able to add multiple deadnames in order to account for this, or nicknames as well.

### LINKED ISSUE #59: Add option to removes nicknames and second middle names?
My deadname has two middle names and sometimes nicknames are used in websites I'm on. I think it'd be cool to do this.

### LINKED ISSUE #61: Cant have two last names
You are unable to put two last names in the last name slot. when you do it glitches out and never stops putting the last name. Otherwise very good tool, thank you

### LINKED ISSUE #62: addition to extension
I have two names that people always use when addressing me. One of them is a nickname that i really hate hearing but i only have to option to change one name. Im not sure if it is possible to add a second name to the remover but if so that would be fantastic

### LINKED ISSUE #70: I have two first names
my first name consists of two names, not joined by a hyphen,  just a space. my full first name is used in official school documents/websites. when emailing a teacher they tend to use just the one name instead of my full first name. if i put my full first name as my dead name then it doesn't change the one part of my first name that teachers use. if i get rid of my full first name and just put the name teachers us then the other half of my dead name shows up along with the name i chose. i tried to put the second name of my first name as my middle name but it just doesn't get rid of it. 

i suggest maybe adding another first name box that can be added if needed. for example i would put the first half my my deadname in the first box and the second part of my deadname in the second box. this way the whole first dedname is changed along with just the first half, aka nickname for your deadname.

im not sure if this makes any sense. please let me know if you can do anything to help me and maybe others out

### LINKED ISSUE #73: More that one form of a given name?
Hey there, this extension is really awesome! I just ran into a little hiccup, though.  I have 2 forms of my birth name that get used:

- PrimarName-SecondaryName MiddleName LastName
- PrimaryName MiddleName LastName

Its not a middle name, and I know some people who have names that are:

- PrimaryName SecondaryName MiddleName LastName

Is there any way to account for having what amounts to 2 versions of a first name?

### LINKED ISSUE #74: feature suggestion: multiple names to swap
Having the ability to swap more than just one name. This would be great because you could add more peoples names other than your own. It also would be a hot fix to some other current limitations of the app around things such as nicknames and names longer than 3 words. (although custom length names and nickname support would be amazing as well)

### LINKED ISSUE #79: multiple deadnames
I think that there should be multiple deadnames. I had a couple nicknames and I still have to see them.

### LINKED ISSUE #80: suggestion
you should allow a way to put in different forms of your dead name so it can be changed. For example, if someone has to use their deadname for their Gmail,  or if they have a dead nickname, it would be nice to have that changed as well so we don't have to see it. So, let's say someone's name is Teo Dal, their email, (teodal@gmail.com) won't be changed if they simply put in Teo Dal in the deadname slot, and if they put in teodal in the deadname category of the extension instead, the extension will only change the Gmail, and nothing else. I hope that makes sense, and I hope it can change soon! thanks for making this life-changing extension!
-Victor

### LINKED ISSUE #94: Beep
Maybe add the ability to add different deadnames, like full name and nickname?

### LINKED ISSUE #99: Two deadnames?
So, I saw this extension and it's great and perfect so far! so far, the big issue I'm running into though is that I go by two different names. One is my real name, and one is a shortened version of my name. Is there any way to change the extension so that you can put in more than one name? Thanks.

### LINKED ISSUE #100: Adding an extra name place
So, I have two dead names, one is my full first name and the other was a nickname. All my family calls me by the nickname and my school calls me by my full name, but i can only block out one. It's amazing to see my family call me elles, even though it isn't real, but I also don't wanna see my other name either. thanks for reading?

### LINKED ISSUE #101: Feature Suggestion: Two Last Names
I have two last names and at the begining I was putting both names in one slot but normaly people use only one last name when refering to me, but in school emails and works its my full name so I still get to see my deadname one way or the other.

### LINKED ISSUE #104: Feature request: field for dead-nickname
Hi, could you add a feature to add a dead-nickname that might aper on sites instead of the dead-firstname? if not thats oki just wondering if it is possible at all

### LINKED ISSUE #107: Multiple Deadnames
Such as Lachlan/Lockie

Maybe use an array of deadnames, and check over them in a for loop

### LINKED ISSUE #110: Suggesting a feature
Dear Developers,
i cant begin to say how much i appreciate this feature! I do however have a suggestion. I think it would be great if we could enter multiple deadnames... i have dead nicknames that most of my teachers call me but my google classroom calls me by my full deadname. i have it set to my full deadname but it would be great to be able to also replace my dead nicknames. 
Thank you! -Michael

### LINKED ISSUE #112: New Names
is there a way that in a future update that more columns of names can be added? I filled out my name already but I have nicknames people still call me and I would like to fill those out too but there's no more room for them

### LINKED ISSUE #114: multiple deadnames
is it possible to add multiple deadnames (because I have a given name and a nickname) that are both deadnames

### LINKED ISSUE #119: Multiple deadnames
I think a useful option to be added would be multiple deadnames to add, because I know I personally have my full name and then what most people called me and it would be useful to be able to hide both!

### LINKED ISSUE #123: Input display problem on Firefox for Ubuntu
Default text input size is 244px on some versions of firefox. Not really a big deal. You could add `input[type=text]{ max-width: 100%}` to keep the inputs from overflowing without changing anything else. Thanks for the extension <3

dname_remo_glitch

### LINKED ISSUE #128: nicknames
i think you should have an option it the deadname remover bc sometimes we have a nickname that is also our deadname that we don't want to see I get called both my full name and nickname and I would really appreciate if there was a feature where I wouldn't have to do that.

### LINKED ISSUE #129: This might be helpful
My deadname has a lot of variations that my teachers and some friends use like really closely related nicknames or things like that, so i suggest adding a feature that allows you to put more than one variation of your deadname, please concider this and thank you for listening to me. Also thank you for making such a helpful thing.

### LINKED ISSUE #130: Name shortenings
First of all - awesome job on the extention - it's super usefull and I love it :)
Second of all I'd love to make a suggestion, maybe make it so that it can also replace name shortenings? For example, John Smith shortened to jsmith
It would be awesome since my school loves to use that format for a lot of things

### LINKED ISSUE #131: Incredible extension
This extension is amazing and has been super helpful in allowing me to use my name while it isn't yet legal, as well as try out different names if I choose. It doesn't always work, but the majority of the time it does and that's all I can ask for. If I were to make a suggestion, maybe add the option to have multiple different ways to spell a name blocked out? Like me for example, where my deadname is sometimes spelled with a special character or symbol above the letter.

### LINKED ISSUE #134: nickname
hi! i just wanted to say that i really love this extension! i just had a quick suggestion, i have a birthname and a nickname from my birthname, i was wondering if you could add something so that people can change multiple names? that would be great!

### LINKED ISSUE #135: Multiple Spellings of Deadname
Maybe I missed it but if not can you add an option for multiple spellings of a name? It still makes me super uncomfortable if I see other spelling types of the name.

### LINKED ISSUE #138: maybe add more deadname stuff for nicknames
there are things this wont detect like, deadnames in all caps and nicknames. maybe add an extra function to detect them thank you for making this though it helps a lot :)

### LINKED ISSUE #144: suggestion
maybe add an option to put a shortened version of ur deadname ?? idk my school uses the long version but ppl who im not out 2 yet use the shortened 1 so idk,, im not sure if this is an option already but if it is pls tell me how to get it ! thx :)

### PR DESCRIPTION
**Pull request by Gusted**
- Make settings more modular under the hood.
- Give certain files a appropriate folder.
- Added a clean-up function that always clean-up any previous work done to the site.
- Performance improvements to `loadNames` function.
- Optimize hide logic.
- Use esbuild(faster & simpler) instead of grunt & webpack.
- Compile new format of `user.js`, uses require instead of full de-bloated `user.js`
- Resolves #144
- Resolves #138
- Resolves #135
- Resolves #134
- Resolves #131
- Resolves #130
- Resolves #129
- Resolves #128
- Resolves #123
- Resolves #119
- Resolves #114
- Resolves #112
- Resolves #110
- Resolves #107
- Resolves #104
- Resolves #101
- Resolves #100
- Resolves #99
- Resolves #94
- Resolves #80
- Resolves #79
- Resolves #74
- Resolves #73
- Resolves #70
- Resolves #62
- Resolves #61
- Resolves #59
- Resolves #58
- Resolves #53
- Resolves #50
- Resolves #48
- Resolves #43
- Resolves #42
- Resolves #39
- Resolves #38
- Resolves #32
- Resolves #27
- Resolves #26
- Resolves #25
- Resolves #18
- Resolves #13
- Resolves #12
- Resolves #11
- Resolves #10
- Resolves #6
- Resolves #1

### CODE REVIEW

**Comment by WillHayCode** [comment]
I'll have a look at this over the weekend, cheers :smile:

**Comment by Gusted** [comment]
> 
> 
> I'll have a look at this over the weekend, cheers 😄

Sure things!

**Comment by Gusted** [comment]
I think it costed more time to go trough all issues than implementing the nick-name feature 😅

**Review by fredwilby — COMMENTED** [review]
Hi, new to this repo, and I was trying to get this to build on linux, but noticed there are some issues:

- Double backslashes in package.json paths (I thought forward slashes were cross-platform at least wrt to modern windows version; backslashes definitely won't work on linux and possibly not MacOS)
- Capital 'src/Types.ts' imported as 'types'
- fs-extra version added is incompatible w/ node 8 (not a lot of reaason not to go to at least node 10 IMO, and this fixes the issue, but should probably be updated in the docs).

After fixing these issues locally I'm able to build and run the branch successfully. I'm happy to put up a PR with these fixes (or however else they should be contributed), but I've never actually contributed to OSS before, so not sure how you'd like that to be done.

**Comment by Gusted** [comment]
> Double backslashes in package.json paths (I thought forward slashes were cross-platform at least wrt to modern windows versions; backslashes definitely won't work on linux and possibly not MacOS)

Woops 😅 

> Capital 'src/Types.ts' imported as 'types'

Woops, where?

> fs-extra version added is incompatible w/ node 8

Didn't knew that, that will be a little update in the readme. As the LTS of node is anyway v12.x so it shouldn't be a big problem to make sure it's Node LTS or higher.

**Comment by fredwilby** [comment]
@Gusted It's imported lowercase everywhere it's imported as far as I can tell, looks like the easiest fix is to rename the src file to lowercase. When I fixed locally I thought there was one place it was referenced as uppercase, but I can't seem to find that now so I may be misremembering.

**Comment by Gusted** [comment]
> 
> 
> @Gusted It's imported lowercase everywhere it's imported as far as I can tell, looks like the easiest fix is to rename the src file to lowercase. When I fixed locally I thought there was one place it was referenced as uppercase, but I can't seem to find that now so I may be misremembering.

Nope, your not. It seems my git client wasn't pushing the new name of types.ts(Which was for me not capitalized), So I've now fixed it by removing the file and than creating a new file with the correct name.

**Comment by Gusted** [comment]
I've tested it trough and trough for a good week, I've only noticed a couple bugs which I've already fixed in this PR.
I think it's a good idea to merge it and see if the users notice any other bugs and let them meet the Live-Update and Nickname Support.

**Comment by WillHayCode** [comment]
Sorry for the delay - really incredible stuff! I'm submitting the update tonight.

For some reason, `fs-extra` isn't agreeing with my computer, but when I copied the files manually it worked fine. I'll investigate that later though, it's small potatoes.

**Comment by Gusted** [comment]
> Sorry for the delay - really incredible stuff! I'm submitting the update tonight.

No problems 🥂 

> For some reason, fs-extra isn't agreeing with my computer, but when I copied the files manually it worked fine. I'll investigate that later though, it's small potatoes.

Hmm, maybe @fredwilby: `fs-extra version added is incompatible w/ node 8 (not a lot of reaason not to go to at least node 10 IMO, and this fixes the issue, but should probably be updated in the docs).` A simple older Node version is the problem?

Regards,
Gusted

**Pull request merged**
